if(!EC)var EC={}
EC.Header={}
EC.Header.BindEvents=function(){var $pillars=$('[data-selector="navigation"] [data-selector="pillar"]'),$pillarNavigations=$('[data-selector="navigation"] [data-selector="pillar-navigation"]'),$pillarSubmenuNavigations=$('[data-selector="navigation"] [data-selector="pillar-submenu-navigation"]'),$menuMobile=$('[data-selector="navigation"] [data-selector="mobile-navigation-menu"]'),$menuNavigationMobile=$('[data-selector="navigation"] [data-selector="mobile-navigation-menu-navigation"]'),$pillarsMobile=$('[data-selector="navigation"] [data-selector="mobile-navigation-menu-pillar"]'),$pillarsListMobile=$('[data-selector="navigation"] [data-selector="mobile-navigation-menu-pillars"]'),$pillarsItemMobile=$('[data-selector="navigation"] [data-selector="mobile-navigation-menu-item"]')
$personalAreaNavigation=$('[data-selector="navigation"] [data-selector="personal-area-navigation"]'),$personalAreaSubmenuNavigations=$('[data-selector="navigation"] [data-selector="desktop-personal-area-submenu"]'),$notificationsNavigation=$('[data-selector="navigation"] [data-selector="desktop-notifications-menu-navigation"]'),$personalAreaNavigationMobile=$('[data-selector="navigation"] [data-selector="mobile-personal-area-navigation"]'),$personalAreaSubmenuNavigationsMobile=$('[data-selector="navigation"] [data-selector="mobile-personal-area-submenu"]'),$marketingElement=$('[data-selector="marketing-element"]'),$marketingElementCloseButton=$('[data-selector="marketing-element-close-button"]'),$marketingElementContent=$('[data-selector="marketing-element-content"]'),$searchToggler=$('[data-selector="toggle-sticky-search"]');$desktopSkinToggler=$('[data-selector="desktop-skin-toggler"]');EC.Header.SetPillars($pillars,$pillarNavigations,$personalAreaNavigation,$personalAreaNavigationMobile,$notificationsNavigation,$searchToggler,$menuNavigationMobile,$menuMobile);EC.Header.SetPillarsSubmenus($pillarSubmenuNavigations);EC.Header.SetPersonalAreaMenu($personalAreaNavigation,$personalAreaNavigationMobile,$pillarNavigations,$notificationsNavigation,$searchToggler,$menuNavigationMobile,$menuMobile);EC.Header.SetPersonalAreaSubmenus($personalAreaSubmenuNavigations,$personalAreaSubmenuNavigationsMobile);EC.Header.SetNotificationsMenu($notificationsNavigation,$personalAreaNavigation,$personalAreaNavigationMobile,$pillarNavigations,$searchToggler,$menuNavigationMobile,$menuMobile);if($marketingElementContent.length>0)EC.Header.SetMarketingElement($marketingElement,$marketingElementContent,$marketingElementCloseButton);EC.Header.ToggleSearch($searchToggler,$personalAreaNavigation,$personalAreaNavigationMobile,$pillarNavigations,$notificationsNavigation,$menuNavigationMobile,$menuMobile);EC.Header.SetStickyNavigation(200,$marketingElement,$marketingElementContent,$desktopSkinToggler,$pillarNavigations,$personalAreaNavigation);EC.Header.SetPillarsMobile($menuMobile,$pillarsMobile,$pillarsListMobile,$pillarsItemMobile,$menuNavigationMobile);EC.Header.ResetMenuListener($pillarNavigations,$personalAreaNavigation);EC.Header.FlickityHideArrows();EC.Header.CloseNewsletterCallOut();}
EC.Header.SetPillarsMobile=function($menuMobile,$pillarsMobile,$pillarsListMobile,$pillarsItemMobile,$menuNavigationMobile){$pillarsMobile.on('click',function(event){$pillarsListMobile.hide();$pillarsItemMobile.hide();$currentMobilePillar=$(this).data("value");$('#'+$currentMobilePillar).show();$('#mobile-navigation-menu-contact').hide();$('#mobile-navigation-menu-home').show();});$menuNavigationMobile.on('change',function(event){var $classNavigationOpen='icon-menu navigation-menu__icon relative';var $classNavigationClose='icon-x navigation-menu__icon relative';if($menuNavigationMobile.prop("checked")==true){$menuMobile.attr('class',$classNavigationClose);EC.Header.DisablePersonalAreaMenu($personalAreaNavigation);EC.Header.DisablePersonalAreaMenuMobile($personalAreaNavigationMobile);EC.Header.DisableNotificationsMenu($notificationsNavigation);EC.Header.DisableSearch($searchToggler);}
else{$menuMobile.attr('class',$classNavigationOpen);$(".accordion>li>ul.show").removeClass("show");$(".accordion>li>ul.inner").hide();$('.toggle>i.icon').removeClass('icon-chevron-up').addClass('icon-chevron-down');}
$pillarsListMobile.show();$('#mobile-navigation-menu-contact').show();$('#mobile-navigation-menu-home').hide();$pillarsItemMobile.hide();});$('nav .toggle').click(function(event){event.preventDefault();var $this=$(this);if($this.children('i.icon.icon-chevron-up').length==0){if($this.next().hasClass('show')){$this.next().removeClass('show');$this.next().slideUp(350);}else{$this.parent().parent().find('li .inner').removeClass('show');$this.parent().parent().find('li .inner').slideUp(350);$this.next().toggleClass('show');$this.next().slideToggle(350);}
$('nav .toggle>i.icon').removeClass('icon-chevron-up').addClass('icon-chevron-down');if($this.children('.icon').hasClass('icon-chevron-down')){$this.children('.icon').removeClass('icon-chevron-down').addClass('icon-chevron-up');}else{$this.children('.icon').removeClass('icon-chevron-up').addClass('icon-chevron-down');}}else{$('nav .toggle>i.icon').removeClass('icon-chevron-up').addClass('icon-chevron-down');$this.next().removeClass('show');$this.next().slideUp(350);}});$('#mobile-navigation-menu-home').on('click',function(event){$pillarsListMobile.show();$('#mobile-navigation-menu-contact').show();$('#mobile-navigation-menu-home').hide();$("nav .accordion>li>ul.show").removeClass("show");$("nav .accordion>li>ul.inner").hide();$('nav .toggle>i.icon').removeClass('icon-chevron-up').addClass('icon-chevron-down');$pillarsItemMobile.hide();});}
EC.Header.DisableSetPillarsMobile=function($menuMobile,$menuNavigationMobile){$menuNavigationMobile.prop('checked',false);$menuMobile.attr('class','icon-menu navigation-menu__icon relative');}
EC.Header.SetPillars=function($pillars,$pillarNavigations,$personalAreaNavigation,$personalAreaNavigationMobile,$notificationsNavigation,$searchToggler,$menuNavigationMobile,$menuMobile){$pillarNavigations.on('change',function(event){EC.Header.DisablePersonalAreaMenu($personalAreaNavigation);EC.Header.DisablePersonalAreaMenuMobile($personalAreaNavigationMobile);EC.Header.DisableNotificationsMenu($notificationsNavigation);EC.Header.DisableSearch($searchToggler);EC.Header.DisableSetPillarsMobile($menuMobile,$menuNavigationMobile);EC.Header.DisableAutoSuggest();var $currentPillarNavigation=$(event.target),$currentPillar=$currentPillarNavigation.parents('[data-selector="pillar"]');$pillarNavigations.not($currentPillarNavigation).prop('checked',false);$pillars.removeClass('active inactive');if($currentPillarNavigation.prop('checked')){$currentPillarNavigation.parents('[data-selector="pillar"]').addClass('active');$pillars.not($currentPillar).addClass('inactive');}});}
EC.Header.SetPillarsSubmenus=function($pillarSubmenuNavigations){$pillarSubmenuNavigations.on('change',function(event){var $pillarSubmenuNavigationsLabels=$pillarSubmenuNavigations.siblings('label'),$currentPillarSubmenuNavigation=$(event.target);$pillarSubmenuNavigations.not($currentPillarSubmenuNavigation).prop('checked',false);$pillarSubmenuNavigationsLabels.removeClass('active');if($currentPillarSubmenuNavigation.prop('checked')){$currentPillarSubmenuNavigation.siblings('label').addClass('active');}
$('nav [data-background-image]').each(function(){$(this).css('background-image',"url("+$(this).data('background-image')+")");});});}
EC.Header.SetPersonalAreaMenu=function($personalAreaNavigation,$personalAreaNavigationMobile,$pillarNavigations,$notificationsNavigation,$searchToggler,$menuNavigationMobile,$menuMobile){$personalAreaNavigation.on('change',function(){EC.Header.DisablePillarMenus($pillarNavigations);EC.Header.DisableNotificationsMenu($notificationsNavigation);EC.Header.DisablePersonalAreaMenuMobile($personalAreaNavigationMobile);EC.Header.DisableSearch($searchToggler);EC.Header.DisableSetPillarsMobile($menuMobile,$menuNavigationMobile);EC.Header.DisableAutoSuggest();var $personalAreaNavigationLabel=$personalAreaNavigation.parent().find('[data-selector="desktop-personal-area-menu-navigation"]');$personalAreaNavigationLabel.toggleClass('icon-x icon-user-2');if($personalAreaNavigationLabel.data('logged'))$personalAreaNavigationLabel.toggleClass('personal-area-menu__avatar--logged-in');});$personalAreaNavigationMobile.on('change',function(){EC.Header.DisablePillarMenus($pillarNavigations);EC.Header.DisableNotificationsMenu($notificationsNavigation);EC.Header.DisablePersonalAreaMenu($personalAreaNavigation);EC.Header.DisableSearch($searchToggler);EC.Header.DisableSetPillarsMobile($menuMobile,$menuNavigationMobile);var $personalAreaNavigationMobileLabel=$personalAreaNavigationMobile.parent().find('[data-selector="mobile-personal-area-menu-navigation"]');$personalAreaNavigationMobileLabel.toggleClass('icon-x icon-user-2');;if($personalAreaNavigationMobileLabel.data('logged'))
$personalAreaNavigationMobileLabel.toggleClass('personal-area-menu__avatar--logged-in')});}
EC.Header.SetPersonalAreaSubmenus=function($personalAreaSubmenuNavigations,$personalAreaSubmenuNavigationsMobile){$personalAreaSubmenuNavigations.on('change',function(event){var $currentSubmenuNavigation=$(event.target);$personalAreaSubmenuNavigations.not($currentSubmenuNavigation).prop('checked',false).siblings('label').removeClass('active');if($currentSubmenuNavigation.prop('checked'))
$currentSubmenuNavigation.prev().addClass('active');else
$currentSubmenuNavigation.prev().removeClass('active');});$personalAreaSubmenuNavigationsMobile.on('change',function(event){var $currentSubmenuNavigationMobile=$(event.target);$personalAreaSubmenuNavigationsMobile.not($currentSubmenuNavigationMobile).prop('checked',false).siblings('label').removeClass('active');if($currentSubmenuNavigationMobile.prop('checked'))
$currentSubmenuNavigationMobile.prev().addClass('active');else
$currentSubmenuNavigationMobile.prev().removeClass('active');});}
EC.Header.SetNotificationsMenu=function($notificationsNavigation,$personalAreaNavigation,$personalAreaNavigationMobile,$pillarNavigations,$searchToggler,$menuNavigationMobile,$menuMobile){$notificationsNavigation.on('change',function(){EC.Header.DisablePillarMenus($pillarNavigations);EC.Header.DisablePersonalAreaMenu($personalAreaNavigation);EC.Header.DisablePersonalAreaMenuMobile($personalAreaNavigationMobile);EC.Header.DisableSearch($searchToggler);EC.Header.DisableSetPillarsMobile($menuMobile,$menuNavigationMobile);var $notificationsMenuLabel=$notificationsNavigation.parent().find('[data-selector="desktop-notifications-menu"]');$notificationsMenuLabel.toggleClass('icon-x icon-bell-2');});}
EC.Header.ToggleSearch=function($searchToggler,$personalAreaNavigation,$personalAreaNavigationMobile,$notificationsNavigation,$pillarNavigations,$menuNavigationMobile,$menuMobile){var $searchWrapper=$searchToggler.siblings();$searchToggler.on('click',function(){EC.Header.DisablePillarMenus($pillarNavigations);EC.Header.DisablePersonalAreaMenu($personalAreaNavigation);EC.Header.DisablePersonalAreaMenuMobile($personalAreaNavigationMobile);EC.Header.DisableNotificationsMenu($notificationsNavigation);EC.Header.DisableSetPillarsMobile($menuMobile,$menuNavigationMobile);$searchToggler.toggleClass('icon-search-2 icon-x');$searchWrapper.toggleClass('active hidden');})}
EC.Header.SetMarketingElement=function($marketingElement,$marketingElementContent,$marketingElementCloseButton){$marketingElement.on('click',function(){$marketingElementContent.addClass('active');$marketingElement.addClass('active');});$marketingElementCloseButton.on('click',function(){$marketingElementContent.removeClass('active');$marketingElement.removeClass('active');});}
EC.Header.SetStickyNavigation=function(target,$marketingElement,$marketingElementContent,$desktopSkinToggler,$pillarNavigations,$personalAreaNavigation){var $stickyNavigation=$('[data-selector="navigation"]');$(document).scroll(function(){var scrollTop=$(window).scrollTop();if(scrollTop>=target){$stickyNavigation.addClass('is-fixed');if($(".navigation__menu:hover").length==0)EC.Header.ResetMenu($pillarNavigations,$personalAreaNavigation);}else $stickyNavigation.removeClass('is-fixed');$marketingElementContent.removeClass('active');$marketingElement.removeClass('active');$desktopSkinToggler.prop('checked','');});}
EC.Header.DisablePillarMenus=function($pillarNavigations){$pillarNavigations.prop('checked',false);$('[data-selector="navigation"] .pillar').removeClass('active inactive');}
EC.Header.DisablePersonalAreaMenu=function($personalAreaNavigation){$personalAreaNavigation.prop('checked',false);$personalAreaNavigationLabel=$personalAreaNavigation.parent().find('[data-selector="desktop-personal-area-menu-navigation"]');$personalAreaNavigationLabel.removeClass('icon-x').addClass('icon-user-2');if($personalAreaNavigationLabel.data('logged'))
$personalAreaNavigationLabel.addClass('personal-area-menu__avatar--logged-in');}
EC.Header.DisablePersonalAreaMenuMobile=function($personalAreaNavigationMobile){$personalAreaNavigationMobile.prop('checked',false);$personalAreaNavigationMobileLabel=$personalAreaNavigationMobile.parent().find('[data-selector="mobile-personal-area-menu-navigation"]');$personalAreaNavigationMobileLabel.removeClass('icon-x').addClass('icon-user-2');;if($personalAreaNavigationMobileLabel.data('logged'))
$personalAreaNavigationMobileLabel.addClass('personal-area-menu__avatar--logged-in')}
EC.Header.DisableNotificationsMenu=function($notificationsNavigation){$notificationsNavigation.prop('checked',false);$notificationsNavigation.parent().find('[data-selector="desktop-notifications-menu"]').removeClass('icon-x').addClass('icon-bell-2');}
EC.Header.DisableSearch=function($searchToggler){var $searchWrapper=$searchToggler.siblings();$searchToggler.removeClass('icon-x').addClass('icon-search-2');$searchWrapper.removeClass('active').addClass('hidden');}
EC.Header.DisableAutoSuggest=function(){$("header #divAutoSuggest").hide();$("header #SearchedKeyword").val('');$("nav #divAutoSuggestSticky").hide();$("nav #search").val('');}
EC.Header.ResetMenu=function($pillarNavigations,$personalAreaNavigation){EC.Header.DisablePillarMenus($pillarNavigations);EC.Header.DisablePersonalAreaMenu($personalAreaNavigation);}
EC.Header.ResetMenuListener=function($pillarNavigations,$personalAreaNavigation){$('main').click(function(){EC.Header.ResetMenu($pillarNavigations,$personalAreaNavigation);});}
EC.Header.FlickityHideArrows=function(){$('[data-selector="web4-mobile"] [data-plugin="flickityCarousel"]').on("change.flickity",function(){document.querySelector('[data-selector="web4-mobile"] [data-plugin="flickityCarousel"]').style.marginLeft="2.9rem";document.querySelector('[data-selector="web4-mobile"] [data-plugin="flickityCarousel"]').style.marginRight="2.9rem";if(document.querySelector('[data-selector="web4-mobile"] [aria-label="Previous"][disabled]')!=null){document.querySelector('[data-selector="web4-mobile"] [data-plugin="flickityCarousel"]').style.marginLeft="0";}
if(document.querySelector('[data-selector="web4-mobile"] [aria-label="Next"][disabled]')!=null){document.querySelector('[data-selector="web4-mobile"] [data-plugin="flickityCarousel"]').style.marginRight="0";}});}
EC.Header.CloseNewsletterCallOut=function(){$('.newsletterCallOut__close i').click(function(){$(this).parent().parent('.newsletterCallOut').hide();});}
$(document).ready(function(){EC.Header.BindEvents();});